site_name: Papers Collection
site_url: https://2022hitoss.github.io/papers
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
